#
# project
#
gitProject  = https://github.com/etcd-io/jetcd
gitURL      = git@github.com/etcd-io/jetcd.git

#
# gradle
#
org.gradle.daemon   = false
org.gradle.parallel = false
org.gradle.jvmargs  = -Xmx2048m -XX:MaxMetaspaceSize=512m

#
# test JVM settings
#
org.gradle.test.jvmargs = -Xmx1536m -Xms256m

