[versions]
log4j = "2.25.2"
slf4j = "2.0.17"
guava = "33.5.0-jre"
assertj = "3.27.6"
junit = "6.0.1"
testcontainers = "2.0.2"
protoc = "4.33.1"
protobuf = "4.33.1"
failsafe = "3.3.2"
awaitility = "4.3.0"
checkerFramework = "3.52.0"
errorprone = "2.44.0"
vertx = "5.0.5"
picocli = "4.7.7"
restAssured = "5.5.6"

versionsPlugin = "0.53.0"
errorPronePlugin = "4.3.0"
spotlessPlugin = "8.1.0"
shadowPlugin = "9.2.2"
testLoggerPlugin = "4.0.0"
protobufPlugin = "0.9.5"
nexusPublishPlugin = "2.0.0"
axionReleasePlugin = "1.21.0"
testRetryPlugin = "1.6.4"


[libraries]
slf4j = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }
junit = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
testcontainers = { module = "org.testcontainers:testcontainers", version.ref = "testcontainers" }
protoc = { module = "com.google.protobuf:protoc", version.ref = "protoc" }
failsafe = { module = "dev.failsafe:failsafe", version.ref = "failsafe" }
awaitility = { module = "org.awaitility:awaitility", version.ref = "awaitility" }
picocli  = { module = "info.picocli:picocli", version.ref = "picocli"}
restAssured = { module = "io.rest-assured:rest-assured", version.ref = "restAssured"}

protobufJava = { module = "com.google.protobuf:protobuf-java", version.ref = "protobuf" }

vertxGrpcCommon = { module = "io.vertx:vertx-grpc-common", version.ref = "vertx" }
vertxGrpcClient = { module = "io.vertx:vertx-grpc-client", version.ref = "vertx" }
vertxGrpcServer = { module = "io.vertx:vertx-grpc-server", version.ref = "vertx" }

log4jApi = { module = "org.apache.logging.log4j:log4j-api", version.ref = "log4j" }
log4jCore = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j" }
log4jSlf4j = { module = "org.apache.logging.log4j:log4j-slf4j2-impl", version.ref = "log4j" }
log4j12 = { module = "org.apache.logging.log4j:log4j-1.2-api", version.ref = "log4j" }

checkerQual = { module = "org.checkerframework:checker-qual", version.ref = "checkerFramework" }

errorprone = { module = "com.google.errorprone:error_prone_core", version.ref = "errorprone" }
errorproneAnnotations = { module = "com.google.errorprone:error_prone_annotations", version.ref = "errorprone" }
errorproneJavac = { module = "com.google.errorprone:javac", version = "9+" }

[bundles]
log4j    = [ "log4jApi", "log4jCore", "log4jSlf4j", "log4j12" ]
testing  = ["junit", "assertj" ]


[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadowPlugin" }
protobuf = { id = "com.google.protobuf", version.ref = "protobufPlugin" }
